CREATE TABLE "DELIVERY_ORDER" (
	"ORDER_ID"	number(10)		NULL,
	"TRUCK_TYPE"	varchar2(100)		NULL,
	"FROM_WHERE"	varchar2(100)		NULL,
	"FROM_SPEC"	varchar2(100)		NULL,
	"DEPART_TIME"	timestamp		NULL,
	"TO_WHERE"	varchar2(100)		NULL,
	"TO_SPEC"	varchar2(100)		NULL,
	"CARGO_TYPE"	varchar2(100)		NULL,
	"CARGO_WEIGHT"	number(10)		NULL,
	"CARGO_HELP"	varchar2(100)		NULL,
	"CARGO_SPEC"	varchar2(1000)		NULL,
	"DISTANCE"	number(10)		NULL,
	"TIME"	varchar2(100)		NULL,
	"ETA"	varchar2(100)		NULL,
	"RECOMMEND_COST"	number(10)		NULL,
	"FIX_COST"	number(10)		NULL,
	"CUSTOMER_NAME"	varchar2(100)		NULL,
	"CUSTOMER_TELEPHONE"	varchar2(100)		NULL,
	"ORDER_STATE"	varchar2(100)		NULL,
	"DRIVER_ID"	varchar2(100)		NULL,
	"DRIVER_NAME"	varchar2(100)		NULL,
	"DRIVER_PHONE_NUMBER"	varchar2(100)		NULL,
	"DRIVER_TRUCK_NUMBER"	varchar2(100)		NULL,
	"ORDER_DATE_TIME"	timestamp		NULL,
	"ACCEPT_DATE_TIME"	timestamp		NULL,
	"DEPART_DATE_TIME"	timestamp		NULL,
	"ARRIVE_DATE_TIME"	timestamp		NULL,
	"COMPLETE_DATE_TIME"	timestamp		NULL,
	"CANCEL_DATE_TIME"	timestamp		NULL,
	"CUSTOMER_EVALUATION"	number(1)		NULL,
	"CUSTOMER_COMMENT"	varchar2(1000)		NULL,
	"driver_id2"	varchar2(100)		NULL,
	"driver_password"	varchar2(100)		NULL,
	"dirver_jumin"	varchar2(13)		NULL,
	"driver_license"	varchar2(100)		NULL
);
  CREATE TABLE "SCOTT"."TRUCKER" 
   (	"DRIVER_ID" VARCHAR2(100 BYTE), 
	"DRIVER_PASSWORD" VARCHAR2(100 BYTE), 
	"DRIVER_JUMIN" VARCHAR2(13 BYTE), 
	"DRIVER_LICENSE" VARCHAR2(100 BYTE), 
	"DRIVER_PASSWORD_CHECK" VARCHAR2(100 BYTE), 
	"DRIVER_NAME" VARCHAR2(100 BYTE), 
	"DRIVER_PHONE_NUMBER" VARCHAR2(11 BYTE), 
	"DRIVER_ADDRESS" VARCHAR2(100 BYTE), 
	"DRIVER_EMAIL" VARCHAR2(100 BYTE), 
	"DRIVER_POSITION" VARCHAR2(100 BYTE), 
	"TRUCK_TYPE" VARCHAR2(100 BYTE), 
	"TRUCK_NUMBER" VARCHAR2(100 BYTE), 
	"DRIVER_PICTURE" VARCHAR2(100 BYTE), 
	"DRIVER_EVALUATION" VARCHAR2(100 BYTE), 
	"PERIOD_START" TIMESTAMP (6), 
	"PERIOD_END" TIMESTAMP (6), 
	"PERIOD_NUMBER" NUMBER(10,0), 
	"ORDER_ID" NUMBER(10,0), 
	"CUSTOMER_NAME" VARCHAR2(100 BYTE), 
	"PHONE_NUMBER" VARCHAR2(100 BYTE), 
	"CARGO_TYPE" VARCHAR2(100 BYTE), 
	"FROM_ADDRESS" VARCHAR2(100 BYTE), 
	"HERE_TOSTART" VARCHAR2(100 BYTE), 
	"HERE_TOEND" VARCHAR2(100 BYTE), 
	"CARGO_HELP" VARCHAR2(100 BYTE), 
	"SHIPPING_COST" NUMBER(10,0), 
	"DRIVER_ALLOW" NUMBER(3,0), 
	"DIRVER_REJECT" NUMBER(3,0));
create table Notice_Board
(   notice_number number(5),
    notice_title varchar2(100),
    notice_content varchar2(1000),
    notice_date date,
    notice_hit number(5),
    primary key (notice_number)
    );

create table FAQ_Board
(   faq_number number(5),
    faq_title varchar2(100),
    faq_content varchar2(1000),
    primary key (faq_number)
    );

create table inquiry_board 
 (   inquiry_number number(5), 
	inquiry_name varchar2(60 byte), 
	inquiry_title varchar2(100 byte), 
	inquiry_content varchar2(1000 byte), 
	inquiry_pwd varchar2(15 byte), 
	inquiry_date date, 
	inquiry_hit number(5), 
	inquiry_ref number(5), 
	inquiry_step number(5), 
	inquiry_level number(5), 
	primary key (inquiry_number)
     );