--주문접수DB
CREATE TABLE "DELIVERY_ORDER" (
	"ORDER_ID"	NUMBER(10)		NULL,
	"TRUCK_TYPE"	VARCHAR2(100)		NULL,
	"FROM_WHERE"	VARCHAR2(100)		NULL,
	"FROM_SPEC"	VARCHAR2(100)		NULL,
	"DEPART_TIME"	TIMESTAMP		NULL,
	"TO_WHERE"	VARCHAR2(100)		NULL,
	"TO_SPEC"	VARCHAR2(100)		NULL,
	"CARGO_TYPE"	VARCHAR2(100)		NULL,
	"CARGO_WEIGHT"	NUMBER(10)		NULL,
	"CARGO_HELP"	VARCHAR2(100)		NULL,
	"CARGO_SPEC"	VARCHAR2(1000)		NULL,
	"DISTANCE"	NUMBER(10)		NULL,
	"TIME"	VARCHAR2(100)		NULL,
	"ETA"	TIMESTAMP		NULL,
	"RECOMMEND_COST"	NUMBER(10)		NULL,
	"FIX_COST"	NUMBER(10)		NULL,
	"CUSTOMER_NAME"	VARCHAR2(100)		NULL,
	"CUSTOMER_TELEPHONE"	VARCHAR2(100)		NULL,
	"ORDER_STATE"	VARCHAR2(100)		NULL,
	"DRIVER_ID"	VARCHAR2(100)		NULL,
	"DRIVER_NAME"	VARCHAR2(100)		NULL,
	"DRIVER_PHONE_NUMBER"	VARCHAR2(100)		NULL,
	"DRIVER_TRUCK_NUMBER"	VARCHAR2(100)		NULL,
	"ORDER_DATE_TIME"	TIMESTAMP		NULL,
	"ACCEPT_DATE_TIME"	TIMESTAMP		NULL,
	"DEPART_DATE_TIME"	TIMESTAMP		NULL,
	"ARRIVE_DATE_TIME"	TIMESTAMP		NULL,
	"COMPLETE_DATE_TIME"	TIMESTAMP		NULL,
	"CANCEL_DATE_TIME"	TIMESTAMP		NULL,
	"CUSTOMER_EVALUATION"	NUMBER(1)		NULL,
	"CUSTOMER_COMMENT"	VARCHAR2(1000)		NULL,
	"DRIVER_ID2"	VARCHAR2(100)		NULL,
	"DRIVER_PASSWORD"	VARCHAR2(100)		NULL,
	"DIRVER_JUMIN"	VARCHAR2(13)		NULL,
	"DRIVER_LICENSE"	VARCHAR2(100)		NULL
    );
--==================================================================================================================    
--화물기사DB    
 CREATE TABLE "SCOTT"."DRIVER" (
    "DRIVER_ID" VARCHAR2(100 BYTE), 
	"DRIVER_PWD" VARCHAR2(100 BYTE), 
	"DRIVER_JUMIN" VARCHAR2(13 BYTE), 
	"DRIVER_LICENSE" VARCHAR2(100 BYTE), 
	"DRIVER_PWD_CHECK" VARCHAR2(100 BYTE), 
	"DRIVER_NAME" VARCHAR2(100 BYTE), 
	"DRIVER_PHONE_NUMBER" VARCHAR2(11 BYTE), 
	"DRIVER_ADDR" VARCHAR2(100 BYTE), 
	"DRIVER_EMAIL" VARCHAR2(100 BYTE), 
	"DRIVER_POSITION" VARCHAR2(100 BYTE), 
	"TRUCK_TYPE" VARCHAR2(100 BYTE), 
	"TRUCK_NUMBER" VARCHAR2(100 BYTE), 
	"DRIVER_PHOTO" VARCHAR2(100 BYTE), 
	"DRIVER_EVALUE" VARCHAR2(100 BYTE), 
	"PERIOD_START" TIMESTAMP (6), 
	"PERIOD_END" TIMESTAMP (6), 
	"PERIOD_NUMBER" NUMBER(10,0)
    );
--==================================================================================================================    
 --고객센터DB
CREATE TABLE NOTICE_BOARD
(   NOTICE_NUMBER NUMBER(5),
    NOTICE_TITLE VARCHAR2(100),
    NOTICE_CONTENT VARCHAR2(1000),
    NOTICE_DATE DATE,
    NOTICE_HIT NUMBER(5),
    PRIMARY KEY (NOTICE_NUMBER)
    );

CREATE TABLE FAQ_BOARD
(   FAQ_NUMBER NUMBER(5),
    FAQ_TITLE VARCHAR2(100),
    FAQ_CONTENT VARCHAR2(1000),
    PRIMARY KEY (FAQ_NUMBER)
    );

CREATE TABLE INQUIRY_BOARD 
 (   INQUIRY_NUMBER NUMBER(5), 
	INQUIRY_NAME VARCHAR2(60 BYTE), 
	INQUIRY_TITLE VARCHAR2(100 BYTE), 
	INQUIRY_CONTENT VARCHAR2(1000 BYTE), 
	INQUIRY_PWD VARCHAR2(15 BYTE), 
	INQUIRY_DATE DATE, 
	INQUIRY_HIT NUMBER(5), 
	INQUIRY_REF NUMBER(5), 
	INQUIRY_STEP NUMBER(5), 
	INQUIRY_LEVEL NUMBER(5), 
	PRIMARY KEY (INQUIRY_NUMBER)
     );

select * from DELIVERY_ORDER;
update delivery_order set order_state='order' where order_id=?